### ISSUE TITLE
Feature: Word-Wrap by Default

### ISSUE THREAD

**Issue by kvn-s** [maelvalais/madoko-vscode#2]
Could you please enable automatic word-wrapping by default just like it's done for the built-in Markdown support?

I already did a some research. Basically what has to be added in "package.json" is:
```json
"contributes": {
    "configurationDefaults": {
        "[madoko]": {
            "editor.wordWrap": "on"
        }
    }
}
```

**Comment by maelvls** [comment]
Good idea!
Also, I added some tips on how to re-wrap manually in the README.md:

If you want to "rewrap to 80 characters" manually (`⌥Q` in madoko.net), you
can install the extension **Rewrap** and map the `rewrap.rewrapComment`
command to `⌥Q`:
```json
{
  "command": "rewrap.rewrapComment",
  "key": "alt+q",
  "when": "editorTextFocus"
}
```
For table re-wrapping and auto-arranging, I use **Table Formatter** and map
the table re-wrapping to `⇧⌥Q`:
```json
{
  "command": "extension.table.formatCurrent",
  "key": "shift+alt+q",
  "when": "editorTextFocus"
}
```

Thank you for your feedbacks!

**Comment by kvn-s** [comment]
Thank you very much for implementing it (and the tip). Much appreciated! :)
