### ISSUE TITLE
Feature: Highlight Inline Math

### ISSUE THREAD

**Issue by kvn-s** [maelvalais/madoko-vscode#3]
Hey, it's me again. I'm still having fun with your highlighter (and loving Madoko even more). ;)

Another quick suggestion: I'd like to have inline math, like `$1+2=3$` (see [here](http://madoko.org/reference.html#sec-math)) to be highlighted too. I guess the same color as `&my-entity;` would be fitting. 

Do you think this could be easily implemented?

**Comment by maelvls** [comment]
Hi!
I just implemented this idea in 0.0.4!
![screen shot 2018-03-01 at 15 58 01](https://user-images.githubusercontent.com/2195781/36851365-55d82924-1d69-11e8-88b1-44372a85cc7f.png)

I also fixed the `~ Math` block that wasn't highlighted as latex.

What do you think?

**Comment by kvn-s** [comment]
Looking good. Thanks. :)
